version: '3'
services:
  zookeeper:
    container_name: rasp-zookeeper
    image: zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: rasp-kafka
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "test_topic:1:1" # topic 명:partition 개수:replica 개수
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092 # 내외부 통신에 필요한 프로토콜 지정
      # KAFKA_HEAP_OPTS: "-Xmx400m -Xms400m" # 카프카 브로커 실행시 힙 메모리 지정
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
